name: Update README all day at 16:50

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '50 16 * * *'  # Exécuter chaque jour à 16:50 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Set up Node.js (version 18.19.1)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1'

      # 3. Run the index.js script to update README.md
      - name: Run update script
        run: |
          node index.js

      # 4. Commit changes
      - name: Commit changes
        run: |
          git config --local user.name "lmdr19"
          git config --local user.email "laurent.mordier@gmail.com"
          git add .
          git commit -m ":memo: README.md updated by OctoCommitter"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
